networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel:rw
    depends_on:
      - php
    networks:
      - app-network

  vite:
    image: node:22
    user: node
    working_dir: /var/www/laravel
    volumes:
      - ./src:/var/www/laravel:rw
    ports:
      - "5173:5173"
    command: sh -c "cd /var/www/laravel && npm install && npm run dev"
    networks:
      - app-network
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: |
        client_host=host.docker.internal
        start_with_request=yes
      XDEBUG_TRIGGER: 'yes'
    networks:
      - app-network
    restart: unless-stopped

  pgsql:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pgsql/dumps:/docker-entrypoint-initdb.d  # для инициализации БД
    ports:
      - '${DB_PORT}:5432'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  composer:
    image: composer:latest
    volumes:
      - ./src:/app
    working_dir: /app
    command: composer
    networks:
      - app-network

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel:rw
    entrypoint: ["php", "/var/www/laravel/artisan"]
    networks:
      - app-network
    depends_on:
      - pgsql